# Using Dumpyara & BuildJet

name: ROM Dumper
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM_URL"
        required: true
        default: "https://cdnorg.d.miui.com/OS3.0.302.0.WONCNXM/dali_images_OS3.0.302.0.WONCNXM_20260507.0000.00_16.0_cn_b905b32c3a.tgz"
      GITHUB_ORG:
        description: "GITHUB_ORG"
        required: true
        default: "RandomPush"
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Dumpyara
        run: |
          sudo apt update &> /dev/null
          sudo apt -y install curl python3 wget aria2 &> /dev/null
          git config --global user.name "bot"
          git config --global user.email ""
          git config --global advice.refSyntax false
      - name: Download & Dump ROM
        run: |
          aria2c -o fw.tgz "https://bn.d.miui.com/OS3.0.302.0.WONCNXM/dali_images_OS3.0.302.0.WONCNXM_20260507.0000.00_16.0_cn_b905b32c3a.tgz"
          #curl bashupload.com -T tm.7z
          tar -tf fw.tgz
          
