# Using Dumpyara & BuildJet

name: ROM Dumper
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM_URL"
        required: true
        default: "https://bigota.d.miui.com/V14.0.22.12.26.DEV/miui_ARES_V14.0.22.12.26.DEV_77dab78db5_13.0.zip"
      GITHUB_ORG:
        description: "GITHUB_ORG"
        required: true
        default: "RandomPush"
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: buildjet-8vcpu-ubuntu-2004
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Dumpyara
        run: |
          sudo apt update &> /dev/null
          sudo apt -y install curl python3 wget aria2 &> /dev/null
          curl -sS https://raw.githubusercontent.com/crazystylus/otadump/mainline/install.sh | bash
          git config --global user.name "bot"
          git config --global user.email ""
          git config --global advice.refSyntax false
          git clone -b test https://github.com/zainarbani/dumpyara.git dumpyara &> /dev/null
          cd dumpyara
          chmod +x setup.sh && chmod +x dumpyara.sh
          ORGH=${{github.event.inputs.GITHUB_ORG}}
          sed -i "s|ORG=AndroidDumps|ORG=$ORGH|g" dumpyara.sh
          bash setup.sh &> /dev/null
      - name: Download & Dump ROM
        run: |
          cd dumpyara
          aria2c -j 16 -o rom.zip "${{github.event.inputs.ROM_URL}}"
          7z l rom.zip
          filen=$(7z l -ba rom.zip | grep -vF 'D....' | grep -oP '\S+$' | xargs basename)
          7z rn rom.zip $filen system.img
          bash dumpyara.sh rom.zip $GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
